# .github/workflows/deploy.yml

name: Deploy Hello Notebook Job

on:
  push:
    branches: [ main ]  # Trigger deployment on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/python-notebook-automation/hello-notebook/hello-notebook .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/python-notebook-automation/hello-notebook/hello-notebook

      - name: Deploy to Cloud Run Job
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/python-notebook-automation/hello-notebook/hello-notebook
          gcloud run jobs deploy hello-notebook-job \
            --image $IMAGE_NAME \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --command "python" \
            --args "scripts/run_all.py" \
            --set-env-vars PORT=8080 \
            --max-retries=1 \
            --execution-environment gen2 \
            --task-timeout=3600s
