name: Deploy Cloud Run Jobs

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: python-notebook-automation
  REGION: us-central1
  IMAGE_NAME: us-central1-docker.pkg.dev/python-notebook-automation/hello-notebook/hello-notebook

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and Push Docker Image to Artifact Registry
        run: |
          gcloud builds submit --quiet --tag "$IMAGE_NAME" || true

      - name: Deploy Cloud Run Job - Run All Notebooks
        run: |
          gcloud run jobs deploy hello-notebook-job \
            --image $IMAGE_NAME \
            --region $REGION \
            --project $PROJECT_ID \
            --command "python" \
            --args "scripts/run_all.py" \
            --memory 512Mi \
            --cpu 1

      - name: Deploy Cloud Run Job - Run Specific Notebook (data_audit.ipynb)
        run: |
          gcloud run jobs deploy data-audit-notebook-job \
            --image $IMAGE_NAME \
            --region $REGION \
            --project $PROJECT_ID \
            --command "python" \
            --args "scripts/run_all.py" \
            --memory 512Mi \
            --cpu 1 \
            --set-env-vars NOTEBOOK_NAME=data_audit.ipynb
