name: Deploy to Cloud Run Jobs

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: your-project-id
  REGION: us-central1
  JOB_NAME: my-job-name
  IMAGE_NAME: us-central1-docker.pkg.dev/your-project-id/your-repo/your-image

jobs:
  deploy-job:
    name: Deploy Cloud Run Job
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK (v2)
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Build Docker image
        run: |
          gcloud builds submit --quiet --tag $IMAGE_NAME

      - name: Deploy Cloud Run Job
        run: |
          gcloud run jobs deploy $JOB_NAME \
            --image $IMAGE_NAME \
            --region $REGION \
            --command "python" \
            --args "scripts/run_all.py"

      - name: Verify job deployment
        run: |
          gcloud run jobs describe $JOB_NAME --region $REGION
